### MENTOR  
### create mentor
post http://127.0.0.1:8000/api/mentors
Content-Type: application/json

{
  "name":"al fath",
  "profile":"http://localhost:8000/images/image.png",
  "profession":"backend developer",
  "email":"alfath@gmail.com"
}

### update mentor
put http://127.0.0.1:8000/api/mentors/1
Content-Type: application/json

{
  "name":"tata redha"
}

### get all mentor
get https://dd56-182-2-69-63.ngrok.io/api/mentors

### get mentor by id
get http://127.0.0.1:8000/api/mentors/3

### delete mentor by id
delete http://127.0.0.1:8000/api/mentors/3


### COURSES
### create courses
post http://127.0.0.1:8000/api/courses
Content-Type: application/json

{
  "name":"Kelas Kotlin",
  "certificate":true,
    "thumbnail":"http://localhost:8080/images/1671774061403.png",
  "type":"premium",
  "status":"published",
  "price":150000,
  "level":"beginner",
  "mentor_id":1,
  "description":"Materi kotlin untuk pemula"
}

### update course
put http://127.0.0.1:8000/api/courses/3
Content-Type: application/json

{
  "name":"Kelas Mobile Kotlin",
  "certificate":true,
  "thumbnail":"http://localhost:8080/images/1671774061403.png",
  "type":"premium",
  "status":"published",
  "price":150000,
  "level":"beginner",
  "mentor_id":1,
  "description":"Materi kotlin untuk pemula"
}
### get all courses
get http://127.0.0.1:8000/api/courses

### get detail courses
get http://127.0.0.1:8000/api/courses/3

### delete course
delete http://127.0.0.1:8000/api/courses/2




### CHAPTER
### create chapter
post http://127.0.0.1:8000/api/chapters
Content-Type: application/json

{
  "name":"Introduction Kotlin",
  "course_id":3
}

### update chapter
put http://127.0.0.1:8000/api/chapters/7
Content-Type: application/json

{
  "name":"Introduction Kotlin",
  "course_id":3
}

### get all chapters
get http://127.0.0.1:8000/api/chapters?course_id=

### get detail chapters
get http://127.0.0.1:8000/api/chapters/7

### delete chapter
delete http://127.0.0.1:8000/api/chapters/7



### LESSON
### create lesson
post http://127.0.0.1:8000/api/lessons
Content-Type: application/json

{
  "name":"Sejarah Kotlin",
  "video":"asdcasr",
  "chapter_id":8
}

### update lesson
put http://127.0.0.1:8000/api/lessons/4
Content-Type: application/json

{
  "name":"Dasar Kotlin",
  "chapter_id":8
}

### get lesson
get http://127.0.0.1:8000/api/lessons?chapter_id=8

### get detail lesson by id
get http://127.0.0.1:8000/api/lessons/4

### delete lesson by id
delete http://127.0.0.1:8000/api/lessons/4



### IMAGE COURSE
### create image course
post http://127.0.0.1:8000/api/image-courses
Content-Type: application/json

{
  "image":"http://localhost:8080/images/1671774061403.png",
  "course_id":3
}

### delete image course
delete http://127.0.0.1:8000/api/image-courses/2


#### MY COURSES
### create my course
post http://127.0.0.1:8000/api/my-courses
Content-Type: application/json

{
  "course_id":3,
  "user_id":5
}

### get my course
get http://127.0.0.1:8000/api/my-courses?user_id=1

### course premium
post http://127.0.0.1:8000/api/my-courses/premium
Content-Type: application/json

{
  "user_id":5,
  "course_id":3
}



#### REVIEW
###create review
post http://127.0.0.1:8000/api/reviews
Content-Type: application/json

{
  "user_id":5,
  "course_id":3,
  "rating":5,
  "note":"kelasnya keren bingit" 
}

###update review
put http://127.0.0.1:8000/api/reviews/2
Content-Type: application/json

{
  "rating":3,
  "note":"keren"
}

###delete review
delete http://127.0.0.1:8000/api/reviews/2